// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ex_ocx.h"

/////////////////////////////////////////////////////////////////////////////
// CEx_OCX

IMPLEMENT_DYNCREATE(CEx_OCX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CEx_OCX properties

OLE_COLOR CEx_OCX::GetForeColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_FORECOLOR, VT_I4, (void*)&result);
	return result;
}

void CEx_OCX::SetForeColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_FORECOLOR, VT_I4, propVal);
}

BOOL CEx_OCX::GetBCircle()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CEx_OCX::SetBCircle(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

short CEx_OCX::GetNHatch()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CEx_OCX::SetNHatch(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CEx_OCX operations

short CEx_OCX::CalCircleSize(short rcWidth, short rcHeight)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		rcWidth, rcHeight);
	return result;
}

void CEx_OCX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
